### ISSUE TITLE
It is not generating pin

### ISSUE THREAD

**Issue by hassankhalidmeer** [fbrettnich/WHMCS-SupportPin#1]
I have installed it and followed the steps. It is not generating pin for my support clients.

**Comment by fbrettnich** [comment]
Hello, do you have some more information?
- Is the addon active?
- Is the pin page / widget displayed?
- How exactly do you determine that no PIN is generated?

**Comment by hassankhalidmeer** [comment]
Yes addon is active .
PIN widget is displayed.
But not showing an PIN
On clicking the button for generation of PIN it goes to index page without generating. 
Also tried to manually visit the link by visiting the link: "/index.php?m=supportpin" After my whmcs installed domain and logging in as a client
![image](https://user-images.githubusercontent.com/63909416/107122546-1b877500-68ba-11eb-97e9-e8ef99fe05ad.png)

**Comment by hassankhalidmeer** [comment]
I am using whmcs 8.0 Is it workable for it?

**Comment by fbrettnich** [comment]
The current version was created and tested on WHMCS 7.10.2, I will test it again with V8.1.0

**Comment by hassankhalidmeer** [comment]
Its not working with v8.1

**Comment by fbrettnich** [comment]
The error should be fixed now 👍
Thank you for your help and sorry for the trouble caused
