### ISSUE TITLE
Add it on different location

### ISSUE THREAD

**Issue by Businezz99** [fbrettnich/WHMCS-SupportPin#4]
Does anyone knows how we can add it on a different page? Ex: to be displayed only on support sidebar instead of clientarea homepage?

Or maybe add it in a drop down right next to the notification icon?

Thanks!

**Comment by fbrettnich** [comment]
Currently you can change it in the hooks in the following line:
https://github.com/fbrettnich/whmcs-supportpin-module/blob/531e723f72733266f784f5c4b61aaedfcdd55d9a/modules/addons/supportpin/hooks.php#L19

Maybe it can also be done by the TemplateManager (PR #3) from @ConanDoyl in the future

**Comment by ConanDoyl** [comment]
Yea the TemplateManager can handle different client Templates. 
Currently it's only one Template included, the default one, but it's easy to add a new one. Currently there's no option yet, to change the Template during runtime. 

I think in the future we can add a Settings Page where we can define the Template for the Clientarea and where the Menu Link should be placed, if a Icon next to the Notification Icon, just a drop down menu link or somewhere else, should not be a problem.
 
Let me know what you prefer and i'll check how i can implement that as fast as possible.

**Comment by Businezz99** [comment]
> Currently you can change it in the hooks in the following line:
> https://github.com/fbrettnich/whmcs-supportpin-module/blob/531e723f72733266f784f5c4b61aaedfcdd55d9a/modules/addons/supportpin/hooks.php#L19
> 
> Maybe it can also be done by the TemplateManager (PR #3) from @ConanDoyl in the future

Thanks!
